import './styles/main.css'
import './styles/nav.css'
import './nav'
import './styles/hero.css'
import './hero'
import './styles/section.css'
import './section'
import './styles/carousel.css'
import './carousel'
import './styles/simulator.css'
import './simulator'
import './styles/video.css'
import './video'
import './styles/anotherCarousel.css'
import './anotherCarousel'
import './styles/timeInvest.css'
import './timeInvest'
import './styles/popProds.css'
import './popProds'
import './styles/footer.css'
import './footer'

console.log('indexIsWorking')